repos:
- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    language_version: python3
    args: ['--include=(\.pyi?$)', '--line-length=100']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: flake8
    args: ['--max-line-length=100']
- repo: https://github.com/prettier/prettier
  rev: 2.0.5
  hooks:
    - id: prettier
