language: python
python:
    3.6
before_install:
    - pip install -r bookqlub_api/requirements.txt
    - pip install -r bookqlub_api/requirements_dev.txt
install:
    - pip install bookqlub_api/.
script: pytest --cov=bookqlub_api/bookqlub_api bookqlub_api
after_success:
    - bash <(curl -s https://codecov.io/bash)
