language: python
python:
    3.6
before_install:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
install:
    - pip install .
script: pytest
after_success:
    - codecov
