language: python
python:
    3.6
before_install:
    - pip install -r bookqlub_api/requirements.txt
    - pip install -r bookqlub_api/requirements_dev.txt
install:
    - pip install bookqlub_api/.
script: pytest
after_success:
    - codecov
