language: python
python:
    3.6
before_install:
    - pip install -r bookqlub_api/requirements.txt
    - pip install -r bookqlub_api/requirements_dev.txt
before_script:
    - cd bookqlub_api
install:
    - pip install .
script: pytest
after_success:
    - codecov
